#include <WiFi.h>
#include <WebServer.h>
#include <Preferences.h>

// ===================== PIN CONFIG =====================
// VERIFY THESE AGAINST YOUR ACTUAL WIRING BEFORE USE.
constexpr int PIN_LDR = 34;          // ADC input
constexpr int PIN_IR_EMITTER = 25;   // IR LED driver/output
constexpr int PIN_BUZZER = 26;       // buzzer driver/output

// ===================== NETWORK ========================
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";
WebServer server(80);
Preferences prefs;

// ===================== SYSTEM STATE ====================
enum SystemMode : uint8_t { OFF, ARMED_LOUD, ARMED_SILENT };
SystemMode mode = OFF;

bool laserCommandedOn = false;
bool beamDetected = false;
bool previousBeamDetected = false;
bool alarmActive = false;
unsigned long bootMs = 0;
unsigned long lastSampleMs = 0;
unsigned long lastStatusMs = 0;
unsigned long lastTriggerMs = 0;
uint32_t triggerCount = 0;
uint32_t activationCount = 0;
uint32_t deactivationCount = 0;
int baseline = 0;

// Ring-buffer registry stored in RAM; counters survive reboot through Preferences.
struct EventRecord { uint32_t seconds; uint8_t type; int value; };
constexpr size_t MAX_EVENTS = 80;
EventRecord events[MAX_EVENTS];
size_t eventCount = 0;
size_t eventHead = 0;

enum EventType : uint8_t { EVT_BOOT, EVT_ARM, EVT_DISARM, EVT_MODE, EVT_LASER_ON, EVT_LASER_OFF, EVT_BEAM_BREAK, EVT_BEAM_RESTORE, EVT_ALARM_ON, EVT_ALARM_OFF };

void logEvent(EventType type, int value = 0) {
  events[eventHead] = { (uint32_t)((millis() - bootMs) / 1000UL), (uint8_t)type, value };
  eventHead = (eventHead + 1) % MAX_EVENTS;
  if (eventCount < MAX_EVENTS) eventCount++;
}

void persistCounters() {
  prefs.putUInt("triggers", triggerCount);
  prefs.putUInt("activations", activationCount);
  prefs.putUInt("deactivations", deactivationCount);
}

void sendIR(uint8_t command) {
  // V1 protocol: 32-bit NEC-style frame generated by IRremoteESP8266.
  // To keep V1 dependency-light, this placeholder uses a visible serial/logic
  // pulse encoding. Replace sendIR() with the exact IR transmitter library
  // implementation after the receiver module is identified/tested.
  digitalWrite(PIN_IR_EMITTER, LOW);
  delayMicroseconds(9000);
  digitalWrite(PIN_IR_EMITTER, HIGH);
  delayMicroseconds(4500);
  for (int i = 0; i < 8; ++i) {
    digitalWrite(PIN_IR_EMITTER, LOW);
    delayMicroseconds(560);
    digitalWrite(PIN_IR_EMITTER, HIGH);
    delayMicroseconds((command & (1 << i)) ? 1690 : 560);
  }
  digitalWrite(PIN_IR_EMITTER, HIGH);
}

void commandLaser(bool on) {
  laserCommandedOn = on;
  sendIR(on ? 0xA1 : 0xA0);
  logEvent(on ? EVT_LASER_ON : EVT_LASER_OFF);
}

void setMode(SystemMode newMode) {
  if (mode == newMode) return;
  if (newMode == OFF) {
    mode = OFF;
    commandLaser(false);
    digitalWrite(PIN_BUZZER, LOW);
    alarmActive = false;
    deactivationCount++;
    logEvent(EVT_DISARM);
  } else {
    mode = newMode;
    activationCount++;
    logEvent(EVT_ARM, (int)newMode);
    commandLaser(true);
    // Allow the optical path to settle before evaluating the beam.
    delay(250);
    baseline = analogRead(PIN_LDR);
  }
  persistCounters();
}

void evaluateBeam() {
  int reading = analogRead(PIN_LDR);
  if (mode == OFF) {
    beamDetected = false;
    return;
  }

  // Adaptive threshold: laser-present reading should normally be above baseline.
  // Calibrate baseline while armed and stable; threshold is deliberately wide.
  const int threshold = max(30, baseline / 4);
  beamDetected = reading > threshold;

  if (beamDetected != previousBeamDetected) {
    if (!beamDetected) {
      triggerCount++;
      lastTriggerMs = millis();
      logEvent(EVT_BEAM_BREAK, reading);
      if (mode == ARMED_LOUD) {
        alarmActive = true;
        digitalWrite(PIN_BUZZER, HIGH);
        logEvent(EVT_ALARM_ON);
      }
      persistCounters();
    } else {
      logEvent(EVT_BEAM_RESTORE, reading);
    }
    previousBeamDetected = beamDetected;
  }

  // Slowly track the beam level only when it is present.
  if (beamDetected) baseline = (baseline * 31 + reading) / 32;
}

String modeName() {
  if (mode == ARMED_LOUD) return "ARMED_LOUD";
  if (mode == ARMED_SILENT) return "ARMED_SILENT";
  return "OFF";
}

String jsonStatus() {
  String s = "{";
  s += "\"mode\":\"" + modeName() + "\",";
  s += "\"laser\":" + String(laserCommandedOn ? "true" : "false") + ",";
  s += "\"beam\":" + String(beamDetected ? "true" : "false") + ",";
  s += "\"alarm\":" + String(alarmActive ? "true" : "false") + ",";
  s += "\"ldr\":" + String(analogRead(PIN_LDR)) + ",";
  s += "\"baseline\":" + String(baseline) + ",";
  s += "\"triggers\":" + String(triggerCount) + ",";
  s += "\"activations\":" + String(activationCount) + ",";
  s += "\"deactivations\":" + String(deactivationCount) + ",";
  s += "\"uptime_s\":" + String((millis() - bootMs) / 1000UL);
  s += "}";
  return s;
}

void handleStatus() { server.send(200, "application/json", jsonStatus()); }
void handleArmLoud() { setMode(ARMED_LOUD); server.send(200, "application/json", jsonStatus()); }
void handleArmSilent() { setMode(ARMED_SILENT); server.send(200, "application/json", jsonStatus()); }
void handleDisarm() { setMode(OFF); server.send(200, "application/json", jsonStatus()); }
void handleSilence() { alarmActive = false; digitalWrite(PIN_BUZZER, LOW); logEvent(EVT_ALARM_OFF); server.send(200, "application/json", jsonStatus()); }

void handleEvents() {
  String s = "[";
  for (size_t i = 0; i < eventCount; ++i) {
    size_t idx = (eventHead + MAX_EVENTS - eventCount + i) % MAX_EVENTS;
    if (i) s += ",";
    s += "{\"t\":" + String(events[idx].seconds) + ",\"type\":" + String(events[idx].type) + ",\"value\":" + String(events[idx].value) + "}";
  }
  s += "]";
  server.send(200, "application/json", s);
}

void setup() {
  Serial.begin(115200);
  pinMode(PIN_LDR, INPUT);
  pinMode(PIN_IR_EMITTER, OUTPUT);
  pinMode(PIN_BUZZER, OUTPUT);
  digitalWrite(PIN_IR_EMITTER, HIGH);
  digitalWrite(PIN_BUZZER, LOW);
  bootMs = millis();

  prefs.begin("reactance", false);
  triggerCount = prefs.getUInt("triggers", 0);
  activationCount = prefs.getUInt("activations", 0);
  deactivationCount = prefs.getUInt("deactivations", 0);
  logEvent(EVT_BOOT);

  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Wi-Fi connecting");
  while (WiFi.status() != WL_CONNECTED) { delay(300); Serial.print('.'); }
  Serial.println();
  Serial.print("Dashboard/API: http://"); Serial.println(WiFi.localIP());

  server.on("/api/status", handleStatus);
  server.on("/api/events", handleEvents);
  server.on("/api/arm/loud", handleArmLoud);
  server.on("/api/arm/silent", handleArmSilent);
  server.on("/api/disarm", handleDisarm);
  server.on("/api/alarm/silence", handleSilence);
  server.begin();
}

void loop() {
  server.handleClient();
  if (millis() - lastSampleMs >= 50) {
    lastSampleMs = millis();
    evaluateBeam();
  }
  // Auto-clear a local loud alarm after beam restoration; dashboard can still log it.
  if (alarmActive && beamDetected && millis() - lastTriggerMs > 500) {
    alarmActive = false;
    digitalWrite(PIN_BUZZER, LOW);
    logEvent(EVT_ALARM_OFF);
  }
}
